project: 
  title: "Lab #4: LTER Network Data"
  subtitle: "Ecosystem Science & Sustainability 330""
  author:
    - name: Melissa May
      email: melmay@colostate.edu
  output-dir: docs
  type: website

format:
  html:
    self-contained: true